### ISSUE TITLE
Selected location result always null

### ISSUE THREAD

**Issue by ahmadkq** [blackmann/locationpicker#14]
When viewing the location picker, the selected location and the result always null

![Simulator Screen Shot - iPhone Xʀ - 2019-12-06 at 23 13 32](https://user-images.githubusercontent.com/26964283/70356987-69e85080-187e-11ea-978b-7c5b53b384e5.png)

**Comment by blackmann** [comment]
Hi @ahmadkq, do you just go back or you tap on the selected location??

**Comment by ahmadkq** [comment]
Hi, I do select a point in the map but the "Unnamed location" doesn't change! When i click the it the returns i null. I don't click back.

**Comment by blackmann** [comment]
Hmm, @ahmadkq . Can you please look at the debug logs to see if there's an error? If there is, please post it here so I can help

**Comment by dhorajiaabhishek** [comment]
Me too getting this error , It always return null. 
there is nothing in log, NO exception.

**Comment by blackmann** [comment]
I have rerun tests and I do not face this issues. May I see the code used to start the place picker??

@dhrojiaabhishek @ahmadkq

**Comment by dhorajiaabhishek** [comment]
Sorry , it resoled 
I was getting this error `You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started`

**Comment by blackmann** [comment]
@ahmadkq could you please try and enable billing for your API keys just as @dhorajiaabhishek indicated?

**Comment by ahmadkq** [comment]
@blackmann I already have my billing enabled. I can see this error when navigating to place picker page
"flutter: RangeError (index): Invalid value: Valid value range is empty: 0"

**Comment by DanielSmith1239** [comment]
I am experiencing the same issue. Any luck?

**Comment by ahmadkq** [comment]
I have fixed it. You need to enable the Geocoding API also

**Comment by dinojw10** [comment]
I have the same problem and have already enabled the Grocoding API, however the problem still persist. Any advise? im new to flutter

**Comment by dinojw10** [comment]
> I have fixed it. You need to enable the Geocoding API also
